var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[id]/knowledge/facts/extract/route.js")
R.c("server/chunks/[root-of-the-server]__2cf11884._.js")
R.c("server/chunks/0b7ee_next_c09bab0b._.js")
R.c("server/chunks/0b7ee_next_dist_esm_build_templates_app-route_4a54447a.js")
R.c("server/chunks/[root-of-the-server]__714a9d2a._.js")
R.c("server/chunks/0b7ee_openai_index_mjs_d4d6ab7f._.js")
R.c("server/chunks/0b7ee_next_dist_542ac617._.js")
R.c("server/chunks/b275f_server_app_api_projects_[id]_knowledge_facts_extract_route_actions_8c11437b.js")
R.m(76855)
module.exports=R.m(76855).exports
