var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[id]/chapters/[num]/preview/route.js")
R.c("server/chunks/[root-of-the-server]__f4ece3f0._.js")
R.c("server/chunks/0b7ee_next_c09bab0b._.js")
R.c("server/chunks/0b7ee_next_dist_esm_build_templates_app-route_f5032307.js")
R.c("server/chunks/0b7ee_next_dist_542ac617._.js")
R.c("server/chunks/[root-of-the-server]__714a9d2a._.js")
R.c("server/chunks/0b7ee_openai_index_mjs_d4d6ab7f._.js")
R.c("server/chunks/b275f_server_app_api_projects_[id]_chapters_[num]_preview_route_actions_9a07c95c.js")
R.m(57677)
module.exports=R.m(57677).exports
