var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/projects/new/wizard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e04c966f._.js")
R.c("server/chunks/ssr/novel-workshop_9094fa59._.js")
R.c("server/chunks/ssr/novel-workshop_773ebf63._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f58da86a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3e86610b._.js")
R.c("server/chunks/ssr/0b7ee_7d00aac6._.js")
R.c("server/chunks/ssr/novel-workshop_app_3ca17017._.js")
R.c("server/chunks/ssr/0b7ee_next_dist_client_components_builtin_global-error_0b582b1e.js")
R.c("server/chunks/ssr/novel-workshop_app_395df7e3._.js")
R.c("server/chunks/ssr/0b7ee_next_dist_client_components_fe27de60._.js")
R.c("server/chunks/ssr/0b7ee_next_dist_client_components_builtin_forbidden_7beb78df.js")
R.c("server/chunks/ssr/0b7ee_next_dist_client_components_builtin_unauthorized_fdf4b29a.js")
R.c("server/chunks/ssr/fd28f__next-internal_server_app_projects_new_wizard_page_actions_c0bc56be.js")
R.m(56605)
module.exports=R.m(56605).exports
