// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/bible" | "/projects" | "/projects/[id]/chapters" | "/projects/[id]/edit" | "/projects/[id]/knowledge" | "/projects/[id]/workspace" | "/projects/new" | "/projects/new/wizard"
type AppRouteHandlerRoutes = "/api/bible/characters" | "/api/bible/deprecated" | "/api/bible/plotlines" | "/api/bible/settings" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/audit-outline" | "/api/projects/[id]/chapters" | "/api/projects/[id]/chapters/[num]" | "/api/projects/[id]/chapters/[num]/preview" | "/api/projects/[id]/characters" | "/api/projects/[id]/generate-outline" | "/api/projects/[id]/generate-outline/save" | "/api/projects/[id]/knowledge/characters" | "/api/projects/[id]/knowledge/characters/[charId]" | "/api/projects/[id]/knowledge/facts" | "/api/projects/[id]/knowledge/facts/extract" | "/api/projects/[id]/knowledge/facts/merge" | "/api/projects/[id]/knowledge/outline" | "/api/projects/[id]/knowledge/worldbuilding" | "/api/projects/[id]/outline/[chapterNum]" | "/api/projects/[id]/wizard/ai-characters" | "/api/projects/[id]/wizard/ai-outline" | "/api/projects/[id]/wizard/ai-world" | "/api/projects/[id]/wizard/init" | "/api/projects/[id]/wizard/master-outline" | "/api/projects/[id]/wizard/save-outline" | "/api/projects/[id]/wizard/save-world" | "/api/write" | "/api/write/mock"
type PageRoutes = never
type LayoutRoutes = "/" | "/projects/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/bible/characters": {}
  "/api/bible/deprecated": {}
  "/api/bible/plotlines": {}
  "/api/bible/settings": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/audit-outline": { "id": string; }
  "/api/projects/[id]/chapters": { "id": string; }
  "/api/projects/[id]/chapters/[num]": { "id": string; "num": string; }
  "/api/projects/[id]/chapters/[num]/preview": { "id": string; "num": string; }
  "/api/projects/[id]/characters": { "id": string; }
  "/api/projects/[id]/generate-outline": { "id": string; }
  "/api/projects/[id]/generate-outline/save": { "id": string; }
  "/api/projects/[id]/knowledge/characters": { "id": string; }
  "/api/projects/[id]/knowledge/characters/[charId]": { "id": string; "charId": string; }
  "/api/projects/[id]/knowledge/facts": { "id": string; }
  "/api/projects/[id]/knowledge/facts/extract": { "id": string; }
  "/api/projects/[id]/knowledge/facts/merge": { "id": string; }
  "/api/projects/[id]/knowledge/outline": { "id": string; }
  "/api/projects/[id]/knowledge/worldbuilding": { "id": string; }
  "/api/projects/[id]/outline/[chapterNum]": { "id": string; "chapterNum": string; }
  "/api/projects/[id]/wizard/ai-characters": { "id": string; }
  "/api/projects/[id]/wizard/ai-outline": { "id": string; }
  "/api/projects/[id]/wizard/ai-world": { "id": string; }
  "/api/projects/[id]/wizard/init": { "id": string; }
  "/api/projects/[id]/wizard/master-outline": { "id": string; }
  "/api/projects/[id]/wizard/save-outline": { "id": string; }
  "/api/projects/[id]/wizard/save-world": { "id": string; }
  "/api/write": {}
  "/api/write/mock": {}
  "/bible": {}
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/chapters": { "id": string; }
  "/projects/[id]/edit": { "id": string; }
  "/projects/[id]/knowledge": { "id": string; }
  "/projects/[id]/workspace": { "id": string; }
  "/projects/new": {}
  "/projects/new/wizard": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/projects/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
