// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/bible/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bible">> = Specific
  const handler = {} as typeof import("../../app/bible/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/chapters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/chapters">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/chapters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/knowledge">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/workspace">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new">> = Specific
  const handler = {} as typeof import("../../app/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/new/wizard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new/wizard">> = Specific
  const handler = {} as typeof import("../../app/projects/new/wizard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bible/characters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bible/characters">> = Specific
  const handler = {} as typeof import("../../app/api/bible/characters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bible/deprecated/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bible/deprecated">> = Specific
  const handler = {} as typeof import("../../app/api/bible/deprecated/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bible/plotlines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bible/plotlines">> = Specific
  const handler = {} as typeof import("../../app/api/bible/plotlines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bible/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bible/settings">> = Specific
  const handler = {} as typeof import("../../app/api/bible/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/audit-outline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/audit-outline">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/audit-outline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/chapters/[num]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/chapters/[num]/preview">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/chapters/[num]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/chapters/[num]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/chapters/[num]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/chapters/[num]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/chapters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/chapters">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/chapters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/characters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/characters">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/characters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/generate-outline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/generate-outline">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/generate-outline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/generate-outline/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/generate-outline/save">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/generate-outline/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/characters/[charId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/characters/[charId]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/characters/[charId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/characters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/characters">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/characters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/facts/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/facts/extract">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/facts/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/facts/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/facts/merge">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/facts/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/facts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/facts">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/facts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/outline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/outline">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/outline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/knowledge/worldbuilding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/knowledge/worldbuilding">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/knowledge/worldbuilding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/outline/[chapterNum]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/outline/[chapterNum]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/outline/[chapterNum]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/ai-characters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/ai-characters">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/ai-characters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/ai-outline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/ai-outline">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/ai-outline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/ai-world/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/ai-world">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/ai-world/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/init">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/master-outline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/master-outline">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/master-outline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/save-outline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/save-outline">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/save-outline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/wizard/save-world/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/wizard/save-world">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/wizard/save-world/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/write/mock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/write/mock">> = Specific
  const handler = {} as typeof import("../../app/api/write/mock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/write/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/write">> = Specific
  const handler = {} as typeof import("../../app/api/write/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
