var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__682d4d5f._.js")
R.c("server/chunks/ssr/novel-workshop_9094fa59._.js")
R.c("server/chunks/ssr/0b7ee_next_dist_esm_build_templates_app-page_5da3b3e2.js")
R.c("server/chunks/ssr/[root-of-the-server]__65b4ad8c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3e86610b._.js")
R.c("server/chunks/ssr/0b7ee_7d00aac6._.js")
R.c("server/chunks/ssr/novel-workshop_app_3ca17017._.js")
R.c("server/chunks/ssr/novel-workshop_app_395df7e3._.js")
R.c("server/chunks/ssr/0b7ee_next_dist_client_components_fe27de60._.js")
R.c("server/chunks/ssr/0b7ee_next_dist_client_components_builtin_forbidden_7beb78df.js")
R.c("server/chunks/ssr/novel-workshop__next-internal_server_app__not-found_page_actions_3e76de2d.js")
R.m(10853)
module.exports=R.m(10853).exports
